services:
  db:
    image: postgres:16
    container_name: home_inventory_db_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: home_inventory
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: inventory_app_dev
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://postgres:password@db:5432/home_inventory?schema=public'
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/app # Mount source code
      - /app/node_modules # Prevent node_modules overwrite
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm run start:dev
      "

volumes:
  postgres_data_dev:
